<?php
/**
 * OccurrenceExceedanceProbability
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SDP Property
 *
 * SDP Property API.
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * OccurrenceExceedanceProbability Class Doc Comment
 *
 * @category Class
 * @description occurrenceExceedanceProbability Details
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OccurrenceExceedanceProbability implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'OccurrenceExceedanceProbability';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'oep50' => 'float',
        'oep100' => 'float',
        'oep250' => 'float',
        'oep500' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'oep50' => null,
        'oep100' => null,
        'oep250' => null,
        'oep500' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'oep50' => 'oep50',
        'oep100' => 'oep100',
        'oep250' => 'oep250',
        'oep500' => 'oep500'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'oep50' => 'setOep50',
        'oep100' => 'setOep100',
        'oep250' => 'setOep250',
        'oep500' => 'setOep500'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'oep50' => 'getOep50',
        'oep100' => 'getOep100',
        'oep250' => 'getOep250',
        'oep500' => 'getOep500'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['oep50'] = isset($data['oep50']) ? $data['oep50'] : null;
        $this->container['oep100'] = isset($data['oep100']) ? $data['oep100'] : null;
        $this->container['oep250'] = isset($data['oep250']) ? $data['oep250'] : null;
        $this->container['oep500'] = isset($data['oep500']) ? $data['oep500'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets oep50
     *
     * @return float
     */
    public function getOep50()
    {
        return $this->container['oep50'];
    }

    /**
     * Sets oep50
     *
     * @param float $oep50 50-Year Occurrence Exceedance Probability. Loss level with a 1-in-50 (2%) chance of being exceeded in any given year, based on the largest loss each year.
     *
     * @return $this
     */
    public function setOep50($oep50)
    {
        $this->container['oep50'] = $oep50;

        return $this;
    }

    /**
     * Gets oep100
     *
     * @return float
     */
    public function getOep100()
    {
        return $this->container['oep100'];
    }

    /**
     * Sets oep100
     *
     * @param float $oep100 100-Year Occurrence Exceedance Probability. Loss level with a 1-in-100 (1%) chance of being exceeded in any given year, based on the largest loss each year.
     *
     * @return $this
     */
    public function setOep100($oep100)
    {
        $this->container['oep100'] = $oep100;

        return $this;
    }

    /**
     * Gets oep250
     *
     * @return float
     */
    public function getOep250()
    {
        return $this->container['oep250'];
    }

    /**
     * Sets oep250
     *
     * @param float $oep250 250-Year Occurrence Exceedance Probability. Loss level with a 1-in-250 (0.4%) chance of being exceeded in any given year, based on the largest loss each year
     *
     * @return $this
     */
    public function setOep250($oep250)
    {
        $this->container['oep250'] = $oep250;

        return $this;
    }

    /**
     * Gets oep500
     *
     * @return float
     */
    public function getOep500()
    {
        return $this->container['oep500'];
    }

    /**
     * Sets oep500
     *
     * @param float $oep500 500-Year Occurrence Exceedance Probability. Loss level with a 1-in-500 (0.2%) chance of being exceeded in any given year, based on the largest loss each year.
     *
     * @return $this
     */
    public function setOep500($oep500)
    {
        $this->container['oep500'] = $oep500;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
