<?php
/**
 * SolarRequesterName
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SDP Property
 *
 * SDP Property API.
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SolarRequesterName Class Doc Comment
 *
 * @category Class
 * @description Solar Requester Name
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SolarRequesterName implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SolarRequesterName';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'requester_first_name_or_company_name' => 'string',
        'requester_middle_name_or_middle_initial' => 'string',
        'requester_last_name' => 'string',
        'requester_suffix' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'requester_first_name_or_company_name' => null,
        'requester_middle_name_or_middle_initial' => null,
        'requester_last_name' => null,
        'requester_suffix' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'requester_first_name_or_company_name' => 'requesterFirstNameOrCompanyName',
        'requester_middle_name_or_middle_initial' => 'requesterMiddleNameOrMiddleInitial',
        'requester_last_name' => 'requesterLastName',
        'requester_suffix' => 'requesterSuffix'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'requester_first_name_or_company_name' => 'setRequesterFirstNameOrCompanyName',
        'requester_middle_name_or_middle_initial' => 'setRequesterMiddleNameOrMiddleInitial',
        'requester_last_name' => 'setRequesterLastName',
        'requester_suffix' => 'setRequesterSuffix'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'requester_first_name_or_company_name' => 'getRequesterFirstNameOrCompanyName',
        'requester_middle_name_or_middle_initial' => 'getRequesterMiddleNameOrMiddleInitial',
        'requester_last_name' => 'getRequesterLastName',
        'requester_suffix' => 'getRequesterSuffix'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['requester_first_name_or_company_name'] = isset($data['requester_first_name_or_company_name']) ? $data['requester_first_name_or_company_name'] : null;
        $this->container['requester_middle_name_or_middle_initial'] = isset($data['requester_middle_name_or_middle_initial']) ? $data['requester_middle_name_or_middle_initial'] : null;
        $this->container['requester_last_name'] = isset($data['requester_last_name']) ? $data['requester_last_name'] : null;
        $this->container['requester_suffix'] = isset($data['requester_suffix']) ? $data['requester_suffix'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets requester_first_name_or_company_name
     *
     * @return string
     */
    public function getRequesterFirstNameOrCompanyName()
    {
        return $this->container['requester_first_name_or_company_name'];
    }

    /**
     * Sets requester_first_name_or_company_name
     *
     * @param string $requester_first_name_or_company_name First name of the company or person requesting the solar lien recording.
     *
     * @return $this
     */
    public function setRequesterFirstNameOrCompanyName($requester_first_name_or_company_name)
    {
        $this->container['requester_first_name_or_company_name'] = $requester_first_name_or_company_name;

        return $this;
    }

    /**
     * Gets requester_middle_name_or_middle_initial
     *
     * @return string
     */
    public function getRequesterMiddleNameOrMiddleInitial()
    {
        return $this->container['requester_middle_name_or_middle_initial'];
    }

    /**
     * Sets requester_middle_name_or_middle_initial
     *
     * @param string $requester_middle_name_or_middle_initial Middle name of the company or person requesting the solar lien recording.
     *
     * @return $this
     */
    public function setRequesterMiddleNameOrMiddleInitial($requester_middle_name_or_middle_initial)
    {
        $this->container['requester_middle_name_or_middle_initial'] = $requester_middle_name_or_middle_initial;

        return $this;
    }

    /**
     * Gets requester_last_name
     *
     * @return string
     */
    public function getRequesterLastName()
    {
        return $this->container['requester_last_name'];
    }

    /**
     * Sets requester_last_name
     *
     * @param string $requester_last_name Last name of the company or person requesting the solar lien recording.
     *
     * @return $this
     */
    public function setRequesterLastName($requester_last_name)
    {
        $this->container['requester_last_name'] = $requester_last_name;

        return $this;
    }

    /**
     * Gets requester_suffix
     *
     * @return string
     */
    public function getRequesterSuffix()
    {
        return $this->container['requester_suffix'];
    }

    /**
     * Sets requester_suffix
     *
     * @param string $requester_suffix Suffix name of the person requesting the solar lien recording.
     *
     * @return $this
     */
    public function setRequesterSuffix($requester_suffix)
    {
        $this->container['requester_suffix'] = $requester_suffix;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
