<?php
/**
 * SubjectTransactionDetail
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SDP Property
 *
 * SDP Property API.
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SubjectTransactionDetail Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SubjectTransactionDetail implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SubjectTransactionDetail';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'subject_transaction_recording_date' => 'int',
        'subject_transaction_document_number' => 'string',
        'subject_transaction_document_book_number' => 'string',
        'subject_transaction_document_page_number' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'subject_transaction_recording_date' => 'int32',
        'subject_transaction_document_number' => null,
        'subject_transaction_document_book_number' => null,
        'subject_transaction_document_page_number' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'subject_transaction_recording_date' => 'subjectTransactionRecordingDate',
        'subject_transaction_document_number' => 'subjectTransactionDocumentNumber',
        'subject_transaction_document_book_number' => 'subjectTransactionDocumentBookNumber',
        'subject_transaction_document_page_number' => 'subjectTransactionDocumentPageNumber'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'subject_transaction_recording_date' => 'setSubjectTransactionRecordingDate',
        'subject_transaction_document_number' => 'setSubjectTransactionDocumentNumber',
        'subject_transaction_document_book_number' => 'setSubjectTransactionDocumentBookNumber',
        'subject_transaction_document_page_number' => 'setSubjectTransactionDocumentPageNumber'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'subject_transaction_recording_date' => 'getSubjectTransactionRecordingDate',
        'subject_transaction_document_number' => 'getSubjectTransactionDocumentNumber',
        'subject_transaction_document_book_number' => 'getSubjectTransactionDocumentBookNumber',
        'subject_transaction_document_page_number' => 'getSubjectTransactionDocumentPageNumber'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['subject_transaction_recording_date'] = isset($data['subject_transaction_recording_date']) ? $data['subject_transaction_recording_date'] : null;
        $this->container['subject_transaction_document_number'] = isset($data['subject_transaction_document_number']) ? $data['subject_transaction_document_number'] : null;
        $this->container['subject_transaction_document_book_number'] = isset($data['subject_transaction_document_book_number']) ? $data['subject_transaction_document_book_number'] : null;
        $this->container['subject_transaction_document_page_number'] = isset($data['subject_transaction_document_page_number']) ? $data['subject_transaction_document_page_number'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets subject_transaction_recording_date
     *
     * @return int
     */
    public function getSubjectTransactionRecordingDate()
    {
        return $this->container['subject_transaction_recording_date'];
    }

    /**
     * Sets subject_transaction_recording_date
     *
     * @param int $subject_transaction_recording_date Recording Date of the subject transaction associated with this event. Format = YYYYMMDD.  Document sourced, refers to prior associated transaction.  Typically refers back to the Recording Date of the Deed of Trust/Mortgage.
     *
     * @return $this
     */
    public function setSubjectTransactionRecordingDate($subject_transaction_recording_date)
    {
        $this->container['subject_transaction_recording_date'] = $subject_transaction_recording_date;

        return $this;
    }

    /**
     * Gets subject_transaction_document_number
     *
     * @return string
     */
    public function getSubjectTransactionDocumentNumber()
    {
        return $this->container['subject_transaction_document_number'];
    }

    /**
     * Sets subject_transaction_document_number
     *
     * @param string $subject_transaction_document_number Document Number of the subject transaction associated with this event.  Document sourced, refers to prior associated transaction.  Typically refers back to the Document Number of the Deed of Trust/Mortgage.
     *
     * @return $this
     */
    public function setSubjectTransactionDocumentNumber($subject_transaction_document_number)
    {
        $this->container['subject_transaction_document_number'] = $subject_transaction_document_number;

        return $this;
    }

    /**
     * Gets subject_transaction_document_book_number
     *
     * @return string
     */
    public function getSubjectTransactionDocumentBookNumber()
    {
        return $this->container['subject_transaction_document_book_number'];
    }

    /**
     * Sets subject_transaction_document_book_number
     *
     * @param string $subject_transaction_document_book_number Document Book Number of the subject transaction associated with this event.  Document sourced, refers to prior associated transaction.  Typically refers back to the Document Book Number of the Deed of Trust/Mortgage.
     *
     * @return $this
     */
    public function setSubjectTransactionDocumentBookNumber($subject_transaction_document_book_number)
    {
        $this->container['subject_transaction_document_book_number'] = $subject_transaction_document_book_number;

        return $this;
    }

    /**
     * Gets subject_transaction_document_page_number
     *
     * @return string
     */
    public function getSubjectTransactionDocumentPageNumber()
    {
        return $this->container['subject_transaction_document_page_number'];
    }

    /**
     * Sets subject_transaction_document_page_number
     *
     * @param string $subject_transaction_document_page_number Document Page Number of the subject transaction associated with this event.  Document sourced, refers to prior associated transaction.  Typically refers back to the Document Page Number of the Deed of Trust/Mortgage.
     *
     * @return $this
     */
    public function setSubjectTransactionDocumentPageNumber($subject_transaction_document_page_number)
    {
        $this->container['subject_transaction_document_page_number'] = $subject_transaction_document_page_number;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
