<?php
/**
 * ClimateRiskAR6AnnualExceedanceProbabilityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SDP Property
 *
 * SDP Property API.
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * ClimateRiskAR6AnnualExceedanceProbabilityTest Class Doc Comment
 *
 * @category    Class
 * @description Annual Exceedance Probablility Details
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ClimateRiskAR6AnnualExceedanceProbabilityTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ClimateRiskAR6AnnualExceedanceProbability"
     */
    public function testClimateRiskAR6AnnualExceedanceProbability()
    {
    }

    /**
     * Test attribute "aep50"
     */
    public function testPropertyAep50()
    {
    }

    /**
     * Test attribute "aep100"
     */
    public function testPropertyAep100()
    {
    }

    /**
     * Test attribute "aep200"
     */
    public function testPropertyAep200()
    {
    }

    /**
     * Test attribute "aep500"
     */
    public function testPropertyAep500()
    {
    }
}
