<?php
/**
 * EnrichedLienMortgageRiskTransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SDP Property
 *
 * SDP Property API.
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * EnrichedLienMortgageRiskTransactionTest Class Doc Comment
 *
 * @category    Class
 * @description Mortgage transaction details.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EnrichedLienMortgageRiskTransactionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EnrichedLienMortgageRiskTransaction"
     */
    public function testEnrichedLienMortgageRiskTransaction()
    {
    }

    /**
     * Test attribute "mortgage_composite_transaction_id"
     */
    public function testPropertyMortgageCompositeTransactionId()
    {
    }

    /**
     * Test attribute "enriched_ltv"
     */
    public function testPropertyEnrichedLtv()
    {
    }

    /**
     * Test attribute "multi_or_split_parcel_code"
     */
    public function testPropertyMultiOrSplitParcelCode()
    {
    }

    /**
     * Test attribute "enriched_mortgage_lien_position"
     */
    public function testPropertyEnrichedMortgageLienPosition()
    {
    }

    /**
     * Test attribute "type_code"
     */
    public function testPropertyTypeCode()
    {
    }

    /**
     * Test attribute "purpose_code"
     */
    public function testPropertyPurposeCode()
    {
    }

    /**
     * Test attribute "subordinate_type_code"
     */
    public function testPropertySubordinateTypeCode()
    {
    }

    /**
     * Test attribute "subordinate_type_code_description"
     */
    public function testPropertySubordinateTypeCodeDescription()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "enriched_loan_type_code"
     */
    public function testPropertyEnrichedLoanTypeCode()
    {
    }

    /**
     * Test attribute "enriched_loan_type_code_confidence_rank"
     */
    public function testPropertyEnrichedLoanTypeCodeConfidenceRank()
    {
    }

    /**
     * Test attribute "enriched_interest_rate"
     */
    public function testPropertyEnrichedInterestRate()
    {
    }

    /**
     * Test attribute "enriched_interest_rate_confidence_rank"
     */
    public function testPropertyEnrichedInterestRateConfidenceRank()
    {
    }

    /**
     * Test attribute "enriched_interest_rate_type_code"
     */
    public function testPropertyEnrichedInterestRateTypeCode()
    {
    }

    /**
     * Test attribute "enriched_interest_rate_type_code_confidence_rank"
     */
    public function testPropertyEnrichedInterestRateTypeCodeConfidenceRank()
    {
    }

    /**
     * Test attribute "enriched_term"
     */
    public function testPropertyEnrichedTerm()
    {
    }

    /**
     * Test attribute "enriched_term_confidence_rank"
     */
    public function testPropertyEnrichedTermConfidenceRank()
    {
    }

    /**
     * Test attribute "enriched_term_code"
     */
    public function testPropertyEnrichedTermCode()
    {
    }

    /**
     * Test attribute "enriched_term_code_confidence_rank"
     */
    public function testPropertyEnrichedTermCodeConfidenceRank()
    {
    }

    /**
     * Test attribute "mortgage_date"
     */
    public function testPropertyMortgageDate()
    {
    }

    /**
     * Test attribute "maturity_date"
     */
    public function testPropertyMaturityDate()
    {
    }
}
