<?php
/**
 * LocationSurveyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SDP Property
 *
 * SDP Property API.
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * LocationSurveyTest Class Doc Comment
 *
 * @category    Class
 * @description LocationSurvey
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LocationSurveyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LocationSurvey"
     */
    public function testLocationSurvey()
    {
    }

    /**
     * Test attribute "range"
     */
    public function testPropertyRange()
    {
    }

    /**
     * Test attribute "township"
     */
    public function testPropertyTownship()
    {
    }

    /**
     * Test attribute "section"
     */
    public function testPropertySection()
    {
    }

    /**
     * Test attribute "quarter_section"
     */
    public function testPropertyQuarterSection()
    {
    }
}
