<?php
/**
 * LotTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SDP Property
 *
 * SDP Property API.
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * LotTest Class Doc Comment
 *
 * @category    Class
 * @description Lot
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LotTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Lot"
     */
    public function testLot()
    {
    }

    /**
     * Test attribute "area_acres"
     */
    public function testPropertyAreaAcres()
    {
    }

    /**
     * Test attribute "area_square_feet"
     */
    public function testPropertyAreaSquareFeet()
    {
    }

    /**
     * Test attribute "area_square_feet_usable"
     */
    public function testPropertyAreaSquareFeetUsable()
    {
    }

    /**
     * Test attribute "depth_feet"
     */
    public function testPropertyDepthFeet()
    {
    }

    /**
     * Test attribute "front_feet"
     */
    public function testPropertyFrontFeet()
    {
    }

    /**
     * Test attribute "shape_code"
     */
    public function testPropertyShapeCode()
    {
    }

    /**
     * Test attribute "topography_type"
     */
    public function testPropertyTopographyType()
    {
    }

    /**
     * Test attribute "easement_type_code"
     */
    public function testPropertyEasementTypeCode()
    {
    }
}
