<?php
/**
 * MortgageArmDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SDP Property
 *
 * SDP Property API.
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * MortgageArmDetailTest Class Doc Comment
 *
 * @category    Class
 * @description MortgageArmDetail
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MortgageArmDetailTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MortgageArmDetail"
     */
    public function testMortgageArmDetail()
    {
    }

    /**
     * Test attribute "initial_reset_date"
     */
    public function testPropertyInitialResetDate()
    {
    }

    /**
     * Test attribute "change_interval"
     */
    public function testPropertyChangeInterval()
    {
    }

    /**
     * Test attribute "frequency"
     */
    public function testPropertyFrequency()
    {
    }

    /**
     * Test attribute "calculation_change"
     */
    public function testPropertyCalculationChange()
    {
    }

    /**
     * Test attribute "maximum_interest_rate"
     */
    public function testPropertyMaximumInterestRate()
    {
    }

    /**
     * Test attribute "index_type"
     */
    public function testPropertyIndexType()
    {
    }

    /**
     * Test attribute "change_percent_limit"
     */
    public function testPropertyChangePercentLimit()
    {
    }

    /**
     * Test attribute "initial_change_max_percent"
     */
    public function testPropertyInitialChangeMaxPercent()
    {
    }

    /**
     * Test attribute "lookback_period"
     */
    public function testPropertyLookbackPeriod()
    {
    }

    /**
     * Test attribute "payment_change_date"
     */
    public function testPropertyPaymentChangeDate()
    {
    }

    /**
     * Test attribute "pay_option_indicator"
     */
    public function testPropertyPayOptionIndicator()
    {
    }

    /**
     * Test attribute "interest_only_indicator"
     */
    public function testPropertyInterestOnlyIndicator()
    {
    }

    /**
     * Test attribute "negative_amortization_indicator"
     */
    public function testPropertyNegativeAmortizationIndicator()
    {
    }

    /**
     * Test attribute "prepayment_rider_indicator"
     */
    public function testPropertyPrepaymentRiderIndicator()
    {
    }

    /**
     * Test attribute "category_code"
     */
    public function testPropertyCategoryCode()
    {
    }
}
