<?php
/**
 * MortgageTransactionIndicatorDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SDP Property
 *
 * SDP Property API.
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * MortgageTransactionIndicatorDetailTest Class Doc Comment
 *
 * @category    Class
 * @description MortgageTransactionIndicatorDetail
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MortgageTransactionIndicatorDetailTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MortgageTransactionIndicatorDetail"
     */
    public function testMortgageTransactionIndicatorDetail()
    {
    }

    /**
     * Test attribute "conforming_loan_indicator"
     */
    public function testPropertyConformingLoanIndicator()
    {
    }

    /**
     * Test attribute "equity_loan_indicator"
     */
    public function testPropertyEquityLoanIndicator()
    {
    }

    /**
     * Test attribute "nonconforming_loan_indicator"
     */
    public function testPropertyNonconformingLoanIndicator()
    {
    }

    /**
     * Test attribute "other_subordinate_loan_indicator"
     */
    public function testPropertyOtherSubordinateLoanIndicator()
    {
    }

    /**
     * Test attribute "concurrent_junior_mortgage_indicator"
     */
    public function testPropertyConcurrentJuniorMortgageIndicator()
    {
    }

    /**
     * Test attribute "silent_second_mortgage_indicator"
     */
    public function testPropertySilentSecondMortgageIndicator()
    {
    }

    /**
     * Test attribute "mortgage_upsell_indicator"
     */
    public function testPropertyMortgageUpsellIndicator()
    {
    }

    /**
     * Test attribute "seller_carry_back_indicator"
     */
    public function testPropertySellerCarryBackIndicator()
    {
    }

    /**
     * Test attribute "gse_eligible_mortgage_indicator"
     */
    public function testPropertyGseEligibleMortgageIndicator()
    {
    }
}
