<?php
/**
 * PaceLienTransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SDP Property
 *
 * SDP Property API.
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * PaceLienTransactionTest Class Doc Comment
 *
 * @category    Class
 * @description Pace Lien Transaction
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaceLienTransactionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PaceLienTransaction"
     */
    public function testPaceLienTransaction()
    {
    }

    /**
     * Test attribute "pace_lien_recording_date"
     */
    public function testPropertyPaceLienRecordingDate()
    {
    }

    /**
     * Test attribute "pace_lien_deed_category_type_code"
     */
    public function testPropertyPaceLienDeedCategoryTypeCode()
    {
    }

    /**
     * Test attribute "pace_lien_document_type_code"
     */
    public function testPropertyPaceLienDocumentTypeCode()
    {
    }

    /**
     * Test attribute "pace_lien_recorded_document_number"
     */
    public function testPropertyPaceLienRecordedDocumentNumber()
    {
    }

    /**
     * Test attribute "pace_lien_recorded_document_book_number"
     */
    public function testPropertyPaceLienRecordedDocumentBookNumber()
    {
    }

    /**
     * Test attribute "pace_lien_recorded_document_page_number"
     */
    public function testPropertyPaceLienRecordedDocumentPageNumber()
    {
    }

    /**
     * Test attribute "pace_lien_total_assessment_amount"
     */
    public function testPropertyPaceLienTotalAssessmentAmount()
    {
    }

    /**
     * Test attribute "pace_lien_assessment_date"
     */
    public function testPropertyPaceLienAssessmentDate()
    {
    }

    /**
     * Test attribute "pace_lien_due_date"
     */
    public function testPropertyPaceLienDueDate()
    {
    }
}
