<?php
/**
 * PaceBuyerMailingAddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SDP Property
 *
 * SDP Property API.
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * PaceBuyerMailingAddressTest Class Doc Comment
 *
 * @category    Class
 * @description Pace Buyer Mailing Address
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaceBuyerMailingAddressTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PaceBuyerMailingAddress"
     */
    public function testPaceBuyerMailingAddress()
    {
    }

    /**
     * Test attribute "buyer_mailing_house_number"
     */
    public function testPropertyBuyerMailingHouseNumber()
    {
    }

    /**
     * Test attribute "buyer_mailing_house_number_suffix"
     */
    public function testPropertyBuyerMailingHouseNumberSuffix()
    {
    }

    /**
     * Test attribute "buyer_mailing_house_number2"
     */
    public function testPropertyBuyerMailingHouseNumber2()
    {
    }

    /**
     * Test attribute "buyer_mailing_direction"
     */
    public function testPropertyBuyerMailingDirection()
    {
    }

    /**
     * Test attribute "buyer_mailing_street_name"
     */
    public function testPropertyBuyerMailingStreetName()
    {
    }

    /**
     * Test attribute "buyer_mailing_mode"
     */
    public function testPropertyBuyerMailingMode()
    {
    }

    /**
     * Test attribute "buyer_mailing_quadrant"
     */
    public function testPropertyBuyerMailingQuadrant()
    {
    }

    /**
     * Test attribute "buyer_mailing_unit_number"
     */
    public function testPropertyBuyerMailingUnitNumber()
    {
    }

    /**
     * Test attribute "buyer_mailing_city"
     */
    public function testPropertyBuyerMailingCity()
    {
    }

    /**
     * Test attribute "buyer_mailing_state"
     */
    public function testPropertyBuyerMailingState()
    {
    }

    /**
     * Test attribute "buyer_mailing_zip_code"
     */
    public function testPropertyBuyerMailingZipCode()
    {
    }

    /**
     * Test attribute "buyer_mailing_carrier_route"
     */
    public function testPropertyBuyerMailingCarrierRoute()
    {
    }

    /**
     * Test attribute "buyer_mailing_street_address"
     */
    public function testPropertyBuyerMailingStreetAddress()
    {
    }

    /**
     * Test attribute "buyer_mailing_opt_out_indicator"
     */
    public function testPropertyBuyerMailingOptOutIndicator()
    {
    }
}
