<?php
/**
 * PropertyDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SDP Property
 *
 * SDP Property API.
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * PropertyDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description Property Details
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PropertyDetailsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PropertyDetails"
     */
    public function testPropertyDetails()
    {
    }

    /**
     * Test attribute "actual_year_built"
     */
    public function testPropertyActualYearBuilt()
    {
    }

    /**
     * Test attribute "effective_year_built"
     */
    public function testPropertyEffectiveYearBuilt()
    {
    }

    /**
     * Test attribute "is_residential_property"
     */
    public function testPropertyIsResidentialProperty()
    {
    }

    /**
     * Test attribute "is_new_construction"
     */
    public function testPropertyIsNewConstruction()
    {
    }
}
