<?php
/**
 * PropertyTaxLienTransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SDP Property
 *
 * SDP Property API.
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * PropertyTaxLienTransactionTest Class Doc Comment
 *
 * @category    Class
 * @description Property Tax Lien Transaction.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PropertyTaxLienTransactionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PropertyTaxLienTransaction"
     */
    public function testPropertyTaxLienTransaction()
    {
    }

    /**
     * Test attribute "tax_lien_transaction"
     */
    public function testPropertyTaxLienTransaction()
    {
    }

    /**
     * Test attribute "tax_lien_details"
     */
    public function testPropertyTaxLienDetails()
    {
    }

    /**
     * Test attribute "tax_payer_name"
     */
    public function testPropertyTaxPayerName()
    {
    }

    /**
     * Test attribute "tax_payer_mailing_address"
     */
    public function testPropertyTaxPayerMailingAddress()
    {
    }

    /**
     * Test attribute "original_tax_lien_transaction"
     */
    public function testPropertyOriginalTaxLienTransaction()
    {
    }
}
