<?php
/**
 * SiteLocationDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SDP Property
 *
 * SDP Property API.
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * SiteLocationDataTest Class Doc Comment
 *
 * @category    Class
 * @description SiteLocationData
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SiteLocationDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SiteLocationData"
     */
    public function testSiteLocationData()
    {
    }

    /**
     * Test attribute "clip"
     */
    public function testPropertyClip()
    {
    }

    /**
     * Test attribute "coordinates_parcel"
     */
    public function testPropertyCoordinatesParcel()
    {
    }

    /**
     * Test attribute "coordinates_block"
     */
    public function testPropertyCoordinatesBlock()
    {
    }

    /**
     * Test attribute "location_legal"
     */
    public function testPropertyLocationLegal()
    {
    }

    /**
     * Test attribute "location_survey"
     */
    public function testPropertyLocationSurvey()
    {
    }

    /**
     * Test attribute "neighborhood"
     */
    public function testPropertyNeighborhood()
    {
    }

    /**
     * Test attribute "municipality"
     */
    public function testPropertyMunicipality()
    {
    }

    /**
     * Test attribute "town"
     */
    public function testPropertyTown()
    {
    }

    /**
     * Test attribute "jurisdiction_county"
     */
    public function testPropertyJurisdictionCounty()
    {
    }

    /**
     * Test attribute "cbsa"
     */
    public function testPropertyCbsa()
    {
    }

    /**
     * Test attribute "census_tract"
     */
    public function testPropertyCensusTract()
    {
    }

    /**
     * Test attribute "tax_rate_area"
     */
    public function testPropertyTaxRateArea()
    {
    }

    /**
     * Test attribute "tax_district"
     */
    public function testPropertyTaxDistrict()
    {
    }

    /**
     * Test attribute "land_use_and_zoning_codes"
     */
    public function testPropertyLandUseAndZoningCodes()
    {
    }

    /**
     * Test attribute "lot"
     */
    public function testPropertyLot()
    {
    }

    /**
     * Test attribute "utilities"
     */
    public function testPropertyUtilities()
    {
    }
}
