<?php
/**
 * StructureClassificationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SDP Property
 *
 * SDP Property API.
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * StructureClassificationTest Class Doc Comment
 *
 * @category    Class
 * @description Structure Classification.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StructureClassificationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "StructureClassification"
     */
    public function testStructureClassification()
    {
    }

    /**
     * Test attribute "building_type_code"
     */
    public function testPropertyBuildingTypeCode()
    {
    }

    /**
     * Test attribute "building_class_code"
     */
    public function testPropertyBuildingClassCode()
    {
    }

    /**
     * Test attribute "grade_type_code"
     */
    public function testPropertyGradeTypeCode()
    {
    }

    /**
     * Test attribute "fire_sprinkler_type_code"
     */
    public function testPropertyFireSprinklerTypeCode()
    {
    }

    /**
     * Test attribute "fire_insurance_type_code"
     */
    public function testPropertyFireInsuranceTypeCode()
    {
    }
}
