<?php
/**
 * TaxLienDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SDP Property
 *
 * SDP Property API.
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * TaxLienDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description taxLienDetails
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TaxLienDetailsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TaxLienDetails"
     */
    public function testTaxLienDetails()
    {
    }

    /**
     * Test attribute "tax_lien_alias_type_code"
     */
    public function testPropertyTaxLienAliasTypeCode()
    {
    }

    /**
     * Test attribute "tax_lien_alias_type_code_description"
     */
    public function testPropertyTaxLienAliasTypeCodeDescription()
    {
    }

    /**
     * Test attribute "taxpayer_id_number"
     */
    public function testPropertyTaxpayerIdNumber()
    {
    }

    /**
     * Test attribute "tax_lien_number"
     */
    public function testPropertyTaxLienNumber()
    {
    }

    /**
     * Test attribute "tax_lien_date"
     */
    public function testPropertyTaxLienDate()
    {
    }

    /**
     * Test attribute "tax_lien_period_begin_minimum_date"
     */
    public function testPropertyTaxLienPeriodBeginMinimumDate()
    {
    }

    /**
     * Test attribute "tax_lien_period_end_maximum_date"
     */
    public function testPropertyTaxLienPeriodEndMaximumDate()
    {
    }

    /**
     * Test attribute "tax_lien_last_refiling_or_lien_extension_date"
     */
    public function testPropertyTaxLienLastRefilingOrLienExtensionDate()
    {
    }
}
