<?php
/**
 * TaxPayerNameTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SDP Property
 *
 * SDP Property API.
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * TaxPayerNameTest Class Doc Comment
 *
 * @category    Class
 * @description taxPayerName
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TaxPayerNameTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TaxPayerName"
     */
    public function testTaxPayerName()
    {
    }

    /**
     * Test attribute "taxpayer_first_name"
     */
    public function testPropertyTaxpayerFirstName()
    {
    }

    /**
     * Test attribute "taxpayer_middle_name_or_middle_initial"
     */
    public function testPropertyTaxpayerMiddleNameOrMiddleInitial()
    {
    }

    /**
     * Test attribute "taxpayer_last_name"
     */
    public function testPropertyTaxpayerLastName()
    {
    }

    /**
     * Test attribute "taxpayer_suffix"
     */
    public function testPropertyTaxpayerSuffix()
    {
    }
}
