<?php
/**
 * PropensityControllerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SDP Property
 *
 * SDP Property API.
 *
 * OpenAPI spec version: v2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PropensityControllerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PropensityControllerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for propensityToHELOC
     *
     * Heloc Propensity Score by clip.
     *
     */
    public function testPropensityToHELOC()
    {
    }

    /**
     * Test case for propensityToListForRent
     *
     * Rent Propensity Score by clip.
     *
     */
    public function testPropensityToListForRent()
    {
    }

    /**
     * Test case for propensityToListForSale
     *
     * Sales Propensity Score by clip.
     *
     */
    public function testPropensityToListForSale()
    {
    }

    /**
     * Test case for propensityToPurchaseMortgage
     *
     * Purchase Propensity Score by clip.
     *
     */
    public function testPropensityToPurchaseMortgage()
    {
    }

    /**
     * Test case for propensityToRefinance
     *
     * Refinance Propensity Score by clip.
     *
     */
    public function testPropensityToRefinance()
    {
    }
}
